cv_stock/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path('api/', include('cv_stock_api.urls')),

]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

instead/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

test = 'test'


a = 3

test2 = 'test2'
hh = 65
test3 = 3

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path('api/', include('instead_api.urls')),

]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeProfile.as_view(), name="profiles"),
    path('profile/<str:username>/', views.UserProfile.as_view(), name="user-profile"),
    path('skill/<slug:skill_slug>', views.ProfileBySkill.as_view(), name="skill"),
    path('login/', views.CustomLoginUser.as_view(), name="login-site"),
    path('logout/', views.UserLogout.as_view(), name="logout"),
    path('register/', views.RegisterUser.as_view(), name="register"),
    path('account/', views.UserAccount.as_view(), name="account"),
    path('edit-account/', views.EditAccount.as_view(), name="edit-account"),
    path('create-skill/', views.SkillCreate.as_view(), name="create-skill"),
    path('update-skill/<slug:slug>/', views.SkillUpdate.as_view(), name="update-skill"),
    path('delete-skill/<slug:slug>/', views.SkillDelete.as_view(), name="delete-skill"),
    path('inbox/', views.InboxView.as_view(), name="inbox"),
    path('create-message/<str:username>/', views.CreateMessage.as_view(), name="create-message"),
    path('message/<str:pk>/', views.MessageView.as_view(), name="message"),


]

projects/models.py
from django.db import models
import uuid
from django.db.models import F
from django.utils.text import slugify
from users.models import Profile
from django.dispatch import receiver
from django.db.models.signals import post_delete


class Tag(models.Model):
    name = models.CharField(max_length=100,)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Project(models.Model):
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(default='', null=False, unique=True, db_index=True)
    image = models.ImageField(null=True, blank=True, default="project_images/default.jpg", upload_to='project_images')
    description = models.TextField(null=True, blank=True)
    project_owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE, related_name='projects')
    demo_link = models.CharField(max_length=500, null=True, blank=True)
    source_link = models.CharField(max_length=500, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag, blank=True)
    total_votes = models.PositiveIntegerField(default=0, null=True, blank=True)
    votes_ratio = models.PositiveIntegerField(default=0, null=True, blank=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    @property
    def get_vote_count(self):
        proj_name = self.title
        proj_obj = Project.objects.get(title=proj_name)
        proj_q = Project.objects.filter(title=proj_name)
        Project.objects.filter(title=proj_name).update(total_votes=F('total_votes') + 1)
        total = Project.objects.get(title=proj_name).total_votes
        up_votes = proj_obj.review_set.all().filter(value='up').count()
        ratio = (up_votes / total) * 100
        proj_q.update(votes_ratio=ratio)
        return total, ratio  # return data for tests

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset

    def __str__(self):
        return self.title


class Review(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, auto_created=True)
    VOTE_TYPE = (
        ('up', 'positive review'),
        ('down', 'negative review'),
    )
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    body = models.TextField(blank=True, max_length=300, null=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    class Meta:
        unique_together = [['owner', 'project']]

    def __str__(self):
        return self.value


@receiver(post_delete, sender=Review)
def get_rating(sender, instance, **kwargs):
    if instance:
        proj_name = instance.project
        proj_obj = Project.objects.get(title=proj_name)
        if proj_obj.total_votes != 0:
            proj_obj.total_votes -= 1
            total = proj_obj.total_votes
            up_votes = Project.objects.get(title=proj_name).review_set.all().filter(value='up').count()
            try:
                ratio = (up_votes / total) * 100
                proj_obj.votes_ratio = ratio
            except:
                pass
            proj_obj.save()

users/views.py
from django.contrib import messages
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView, TemplateView, UpdateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import DeleteView, FormView
from .forms import CustomUserCreationForm, ProfileForm, SkillForm, MessageForm, LoginUser
from .models import Profile, Skill


class HomeProfile(ListView):
    template_name = 'users/profiles.html'
    model = Profile
    context_object_name = 'profiles'
    paginate_by = 6

    def get_queryset(self):
        q = self.request.GET.get('q')
        profiles_all = self.model.objects.select_related('user').prefetch_related('skills')
        if q:
            skills = Skill.objects.distinct().filter(name__icontains=q)
            profile_list = profiles_all.distinct().filter(
                Q(name__icontains=q) |
                Q(user__first_name__icontains=q) |
                Q(user__last_name__icontains=q) |
                Q(skills__in=skills))

            profiles_all = profile_list
        return profiles_all


class UserProfile(TemplateView):
    template_name = 'users/user-profile.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        profile = Profile.objects.get(username=self.kwargs['username'])
        context['profile'] = profile
        context['main_skills'] = profile.skills.all()
        context['extra_skills'] = profile.skills.all()
        return context


class ProfileBySkill(ListView):
    template_name = "users/profiles.html"
    model = Skill
    context_object_name = 'profiles'
    paginate_by = 6

    def get_queryset(self):
        skill = get_object_or_404(Skill, slug=self.kwargs['skill_slug'])
        profiles = Profile.objects.select_related('user').prefetch_related('skills').filter(skills__in=[skill])
        return profiles


class CustomLoginUser(LoginView, View):
    page = 'login'  # for check in template
    form_class = LoginUser
    template_name = 'users/login_register.html'

    def get_success_url(self):
        return reverse_lazy('profiles')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['page'] = self.page
        return context


class RegisterUser(CreateView):
    page = 'register'  # for check in template
    template_name = 'users/login_register.html'
    form_class = CustomUserCreationForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['page'] = self.page
        return context

    def get_success_url(self):
        return reverse_lazy('projects')


class UserAccount(LoginRequiredMixin, TemplateView):
    template_name = 'users/account.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        profile = self.request.user.profile
        context['profile'] = profile.user.profile
        context['skills'] = profile.skills.all()
        context['projects'] = profile.projects.all()
        return context


class EditAccount(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'users/profile_form.html'
    model = Profile
    form_class = ProfileForm
    success_url = '/account'
    success_message = 'Account info changed!'

    def get_object(self):
        return self.model.objects.get(id=self.request.user.profile.id)

    def get_context_data(self, **kwargs):
        profile = self.request.user.profile
        form = ProfileForm(instance=profile)
        context = super().get_context_data()
        context['profile'] = profile
        context['form'] = form
        return context


class SkillCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'users/skill_form.html'
    model = Skill
    form_class = SkillForm
    success_url = '/account'
    success_message = 'Skill added!'

    def form_valid(self, form):
        profile = self.request.user.profile
        form.save()
        profile.skills.add(form.instance)
        return super().form_valid(form)


class SkillUpdate(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'users/skill_form.html'
    model = Skill
    form_class = SkillForm
    success_url = '/account'
    success_message = 'Skill changed!'


class SkillDelete(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Skill
    success_url = '/account'
    template_name = 'users/skills.html'
    success_message = 'Skill removed from user!'

    # removing skill related with profile. Not delete it Skill model

    def delete(self, request, *args, **kwargs):
        skill = request.user.profile.skills.get(slug=self.kwargs['slug'])
        return request.user.profile.skills.remove(skill)


class InboxView(LoginRequiredMixin, TemplateView):
    template_name = 'users/inbox.html'

    def get_context_data(self, **kwargs):
        profile = self.request.user.profile
        message_requests = profile.messages.all()
        unread_count = message_requests.filter(is_read=False).count()
        context = super(InboxView, self).get_context_data()
        context['message_requests'] = message_requests
        context['unread_count'] = unread_count
        return context


class CreateMessage(SingleObjectMixin, FormView, SuccessMessageMixin):
    model = Profile
    template_name = 'users/message_form.html'
    form_class = MessageForm
    context_object_name = 'recipient'
    success_url = '/login'

    def get_object(self, queryset=None):
        return self.model.objects.get(username=self.kwargs['username'])

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        try:
            sender = self.request.user.profile
        except:
            sender = None
        message = form.save(commit=False)
        message.sender = sender
        message.recipient = self.get_object()

        if sender:
            message.name = sender.name
            message.email = sender.email
        message.save()
        return super(CreateMessage, self).form_valid(form)


class MessageView(TemplateView):
    template_name = 'users/messages.html'

    def get_context_data(self, **kwargs):
        profile = self.request.user.profile
        message = profile.messages.get(id=self.kwargs['pk'])
        context = super(MessageView, self).get_context_data()
        context['message'] = message
        if not message.is_read:
            message.is_read = True
            message.save()
        return context


class UserLogout(LogoutView):
    template_name = 'users/login_register.html'

# FBV

# def create_message(request, username):
#     recipient = Profile.objects.get(username=username)
#     form = MessageForm()
#
#     try:
#         sender = request.user.profile
#     except:
#         sender = None
#
#     if request.method == 'POST':
#         form = MessageForm(request.POST)
#         if form.is_valid():
#             message = form.save(commit=False)
#             message.sender = sender
#             message.recipient = recipient
#
#             if sender:
#                 message.name = sender.name
#                 message.email = sender.email
#             message.save()
#
#             messages.success(request, 'Your message has been sent')
#             return redirect('user-profile', username=recipient.username)
#
#     context = {'recipient': recipient, 'form': form, }
#     return render(request, 'users/message_form.html', context)

# LOGOUT_REDIRECT_URL = 'login' in settings.py

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data()
    #     context['page'] = 'login'
    #     return context


# @login_required(login_url='login')
# def view_message(request, pk):
#     profile = request.user.profile
#     message = profile.messages.get(id=pk)
#     if message.is_read == False:
#         message.is_read = True
#         message.save()
#     context = {'message': message}
#     return render(request, 'users/messages.html', context)


# @login_required(login_url='login')
# def inbox(request):
#     profile = request.user.profile
#     message_requests = profile.messages.all()
#     unread_count = message_requests.filter(is_read=False).count()
#     context = {
#         'messageRequests': message_requests,
#         'unreadCount': unread_count
#     }
#     return render(request, 'users/inbox.html', context)

# def user_profile(request, username):
#     profile = Profile.objects.get(username=username)
#     main_skills = profile.skills.all()
#     extra_skills = profile.skills.all()
#     context = {'profile': profile, 'main_skills': main_skills,
#                "extra_skills": extra_skills}
#     return render(request, 'users/user-profile.html', context)


# @login_required(login_url='login')
# def edit_account(request):
#     profile = request.user.profile
#     form = ProfileForm(instance=profile)
#
#     if request.method == 'POST':
#         form = ProfileForm(request.POST, request.FILES, instance=profile)
#         if form.is_valid():
#             form.save()
#
#             return redirect('account')
#
#     context = {'form': form, 'profile': profile}
#     return render(request, 'users/profile_form.html', context)


# @login_required(login_url='login')
# def user_account(request):
#     profile = request.user.profile
#

users/templates/users/inbox.html
{% extends 'base.html' %}

{% block content %}
    <main class="inbox my-xl">
        <div class="content-box">
            <h3 class="inbox__title">New messages:(<span>{{ unread_count }}</span>)</h3>
            {% if not message_requests %}
                <span>you have no messages</span>
            {% endif %}

            <br>
            <ul class="messages">
                {% for message in message_requests %}
                    {% if message.is_read == False %}
                        <li class="message message--unread">
                            {% else %}
                        <li class="message">
                    {% endif %}

                <a href="{% url 'message' message.id %}">
                    <span class="message__author">{{ message.name }}</span>
                    <span class="message__subject">{{ message.subject }}</span>
                    <span class="message__date">{{ message.created }}</span>
                </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </main>

{% endblock content %}

users/templates/users/login_register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


{% if page == 'login' %}

    <form style="margin-bottom:40px" class="form-log px-5 py-3 fs-4" method="post">
        {% csrf_token %}


        <p style="text-align: center">Login</p>

        {% for field in form %}

            {{ field.label }}
            {{ field }}

        {% endfor %}

{% for error in form.non_field_errors %}
        <div style="width: 45rem; height: 55px"  class="hide alert alert-danger " id="alert-error">{{ error }}
            <button type="button" class="ml-2 mb-1 btn-close" id="btn-close"></button>
        </div>

    {% endfor %}


        <button style="border-radius: 5px" type="submit" class="mt-3 btn-lg btn btn-primary">Login</button>
        <hr>
        <div>
            <div class="fs-4 ">
                <a class="text-decoration-none text-reset" style="pointer-events: none;">Don't have an account?</a>
                <a style=" border-radius: 8px;margin-left:20px " class="fs-4 btn-lg btn btn-primary w-50"
                   href="{% url 'register' %}" role="button">Register</a>
            </div>
        </div>
        <br>
    </form>

{% else %}

    <form style="margin-bottom:40px" method="POST" action="{% url 'register' %}"
          class="form-log px-5 py-1 fs-4 form-control-lg">
        {% csrf_token %}

        <h3 style="text-align: center">Register</h3>
        <p  style="text-align: center">Create developer account</p>
        {% for field in form %}

            {{ field.label }}
            {{ field }}
        <div style="color: red" class="form-error">{{ field.errors }}</div>
        {% endfor %}
        <input style="margin-top: 10px" class="btn btn-lg btn-primary" type="submit" value="Save"/>
        <div style="margin-bottom: 15px">
            <div class="fs-4" style="margin-top: 10px">
                <a class="text-decoration-none text-reset" style="pointer-events: none;" href="">Already have an account?</a>
                <a style=" border-radius: 15px;margin-left:20px " class="fs-4 btn-lg btn btn-primary w-50"
                   href="{% url 'login' %}" role="button">Login</a>
            </div>
        </div>
    </form>

{% endif %}


{% endblock content %}

users/templates/users/message_form.html
{% extends 'base.html' %}

{% block content %}
<main class=" my-xl ">
    <div class="content-box form-me">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'user-profile' recipient.username  %}"><img src="{{ recipient.image.url }}" alt=""></a>
            <br>
            <p>Message to <span style="font-weight: bold">{{ recipient.username }}</span></p>
            <form class="form" method="POST">
                {% csrf_token %}

                {% if request.user.is_authenticated == False %}
                <div class="form__field">
                    <label for="formInput#text">{{ form.name.label }}</label>
                    {{ form.name }}
                </div>

                <div class="form__field">
                    <label for="formInput#text">{{ form.email.label }}</label>
                    {{ form.email }}
                </div>
                {% endif %}

                <div class="form__field">
                    <label for="formInput#text">{{ form.subject.label }}</label>
                    {{ form.subject }}
                </div>

                <div class="form__field">
                    <label for="formInput#text">{{ form.body.label }}</label>
                    {{ form.body }}
                </div>

                <input class="btn btn-lg  btn-outline-primary  my-md" type="submit" value="Send" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}

users/templates/users/user-profile.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">

    {% if messages %}
        {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
        <div class="main-body" style="margin-top: 20px;">

            <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="{{ profile.image.url }}" alt="Admin"
                                     class="w-50 rounded-circle">
                                <div class="mt-3">
                                    <h4>{{ profile.name }}</h4>
                                    <p class="text-secondary mb-1">{{ profile.intro }}</p>
                                    <a id="btn-log" href="{% url 'create-message' profile.username %}" class="btn btn-lg btn-dark">Message</a>

                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card mt-3">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline">
                                        <circle cx="12" cy="12" r="10"></circle>
                                        <line x1="2" y1="12" x2="22" y2="12"></line>
                                        <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path>
                                    </svg>
                                    Website
                                </h6>
                                <span class="text-secondary">mysite.com</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round" class="feather feather-github mr-2 icon-inline">
                                        <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
                                    </svg>
                                    Github
                                </h6>
                                <span class="text-secondary">github.com</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round"
                                         class="feather feather-twitter mr-2 icon-inline text-info">
                                        <path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path>
                                    </svg>
                                    Twitter
                                </h6>
                                <span class="text-secondary">twitter.com</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round"
                                         class="feather feather-instagram mr-2 icon-inline text-danger">
                                        <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
                                        <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
                                        <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
                                    </svg>
                                    Instagram
                                </h6>
                                <span class="text-secondary">instagram.com</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="mb-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round"
                                         class="feather feather-facebook mr-2 icon-inline text-primary">
                                        <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path>
                                    </svg>
                                    Facebook
                                </h6>
                                <span class="text-secondary">facebook.com</span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-8 fs-4">
                    <div class=" mb-3 ">
                        <div class="card card-body">
                            <div class="row">
                                <div class="col-sm-2">
                                    <h6 class="mb-0 fs-4">About me</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {{ profile.bio }}
                                </div>
                            </div>
                            <hr>

                            <div class="row">
                                <div class="col-sm-2">
                                    <h6 class="mb-0 fs-4">Skills</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    {% for skill in main_skills %}
                                    <a href="{% url 'skill' skill.slug %}" class="skill text-decoration-none tag ">{{ skill.name }}</a>
                                {% endfor %}
                                </div>
                            </div>
                            <div class="row">
                            </div>

                            <div class="row ">
                                <div class="col-sm-12">
                                </div>
                            </div>
                        </div>
                    </div>


                    <h1 style=" font-family: Georgia; font-size: 3rem;"
                        class="text-center devInfo__title">Projects</h1>


{#                    <div style="" class="">#}
                        <div style="margin-left: 5px" >
                            {% for project in profile.project_set.all %}

                                <a href="{% url 'project' project.slug %}"
                                   class="item-child  project text-decoration-none text-reset">
                                    <div class=" card mt-4 "
                                         style="margin-right: 60px; width:30rem;">
                                        <img src="{{ project.image.url }}"
                                             class=" card-img-top text-decoration: none;"
                                             alt="...">
                                        <div class="card-body">
                                            <h3>{{ project }}</h3>
                                            <p class="card-text">{{ project.description|truncatechars:"150" }}</p>
                                            <p class="project--rating">
                                                <span style="font-weight: bold;">votes rating:</span> {{ project.votes_ratio }}</p>
                                            <p class="project--rating">
                                                <span style="font-weight: bold;">total votes:</span> {{ project.total_votes }}</p>
                                            {% for tag in project.tags.all %}
                                                <a href="{% url 'tag' tag.slug %}"
                                                   class="text-decoration-none tag tag--pill tag--main">{{ tag }}</a>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </a>
                            {% endfor %}
                        </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}